# Generated by Django 4.2.4 on 2023-09-22 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="unit_price",
            new_name="unit_price",
        ),
    ]
